#+STARTUP: showall indent
#+STARTUP: hidestars
#+BEGIN_EXPORT html
---
layout: post
title: 2019读书记录
categories: book-review
excerpt: 一部分2019年读过的书
---
#+END_EXPORT

* 2019-03
#+BEGIN_QUOTE
南北战争三百年 \\
作者：李硕 \\
出版社：上海人民出版社
#+END_QUOTE

一本很有趣的书，由作者在清华大学历史专业的博士论文扩充而成，探讨的是一个在历史研究中被严重忽略的问题：中国历史上的战是怎么打的？传统的史书在描述战争是几乎不会描述太多细节，因为着墨之处多在帝王将相的运筹帷幄；而小说又对战争的细节做了太多演绎或者虚构，导致后人难以看到战争的真相。一个例子就是明朝的戚继光已经意识到这个问题，看到了许多百姓甚至的士兵将小说中的演绎当成了战争的真相，比如他提到真的会耍花枪的所谓枪法高手在实战中没有多大用武之地。

书的内容大概可以分两部分：第一部分关于骑兵战术在历史中的变化，尤其是装备（最明显的是马蹬，也包括马槊），政权性质（游牧或农耕）对骑兵战术的演变的影响。第二部分关于4-6世纪南北战争，包括战例分析，政权与战争模式的探讨等。

前几章中关于秦汉以来步兵和骑兵战术的演变，在我看来写的很精彩。通过史书中零星的信息，加上出土文武的佐证，论证得很有说服力。骑兵和步兵的作战模式在秦汉的演变，受到政权性质（游牧民族没有强大的集权，很难用大规模步兵部队对骑兵进行冲击），战马来源（农耕区只能通过有限的贸易渠道获取战马），作战装备（马蹬使得骑兵的冲击作战更加容易）等因素的影响。骑兵在中原地区从最早作为作战的辅助部队（担负警戒，侦察，运输等任务），到和步兵进行联合作战，再到独立作战，从以类似北方游牧族的骑射为主到以冲击战术为主，这期间农耕区域的军队吸收了大量和游牧区域进行作战的经验，并针对自身的社会，经济条件做出了新的发展。同时步兵的军阵也对骑兵的新战术作出了变化，例如步兵的阵形从窄长向宽短演变，更适应骑兵的冲击战术。

第二部分对4-6世纪南北朝时期南北之间的几次战争进行了分析，着重在战争模式以及地理因素对战争进程的影响。北方的南下，着重在长江中上游（以便顺流而下进攻南京）和江淮之间平原的争夺；南方的北伐通常以夺取黄河的关键渡口为目标，为此需要疏通黄河和淮河之间的若干支流和运河，以便船只可以从长江/淮河到达黄河，若能控制洛阳/潼关一带则有机会进攻长安或者华北平原。

除了对战争本身的分析，作者还有对南北政权和经济模式的一些有趣的见解。例如南方经济更发达，但是却没有转化成更强的战斗力，是不是发达的经济带来更自由的思想，从而削弱了战争的动员能力？是不是如果能有更长的一段和平时间让南方的政治/军事模式适应这种更先进的经济模式，就能让经济水平带来更高的军事能力？同时，南北之间的文化差异，也体现在文官集团和武将集团之间的差异和矛盾上，虽然北朝入主南方后都回极力吸收南方的先进文化（通常是统治者带头），但是南北之间根深蒂固的差异还是一直保留下来，甚至带来类似唐代安史之乱这样的矛盾爆发。

这是一本既有深度又有广度的难得用心写的好书，其中很多问题甚至值得单独再写一本。



